### ISSUE TITLE
extract meta data and structured data out of code chunks

### ISSUE THREAD

**Issue by maxoja** [maxoja/qmk-moonlander-layer-stacker#2]
- [x] how many layers
- [x] arrays of string of keymap
- [x] arrays of string of color code
